name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.8

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest tests_unitaires/

    - name: Deploy to PythonAnywhere
      env:
        PA_TOKEN: ${{ secrets.PA_TOKEN }}
      run: |
        curl -X POST -H "Authorization: Token $PA_TOKEN" -d "source_dir=/path/to/code" https://www.pythonanywhere.com/api/v0/user/elimulo/webapps/<app_name>/reload/
