name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  MLFLOW_TRACKING_URI: http://127.0.0.1:5000

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.6

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Start MLflow Server
      run: |
        mlflow server --host 127.0.0.1 --port 5000 &  # Run MLflow server in the background
        echo $! > mlflow_pid.txt

    - name: Run tests
      run: |
        pytest test_unitaires/
 
    - name: Checkout code
      uses: actions/checkout@v3

    # - name: Set up SSH key for authentication
    #   run: |
    #     mkdir -p ~/.ssh
    #     echo "${{ secrets.PA_SSH_KEY }}" > ~/.ssh/id_rsa
    #     chmod 600 ~/.ssh/id_rsa
    #     ssh-keyscan pythonanywhere.com >> ~/.ssh/known_hosts
        
    # - name: Deploy to PythonAnywhere using SCP
    #   run: |
    #     scp -r ./app $PA_USERNAME@pythonanywhere.com:/home/$PA_USERNAME/mysite/
    #   env:
    #     PA_USERNAME: ${{ secrets.PA_USERNAME }}

    # - name: SSH command to restart app on PythonAnywhere
    #   run: |
    #     ssh $PA_USERNAME@pythonanywhere.com "source ~/myenv/bin/activate && cd ~/mysite && streamlit run app.py"
    #   env:
    #     PA_USERNAME: ${{ secrets.PA_USERNAME }}

    - name: Stop MLflow Server
      run: |
        kill $(cat mlflow_pid.txt)
