name: CI/CD Pipeline

on:
  push:
    branches:
      - main

env:
  MLFLOW_TRACKING_URI: http://127.0.0.1:5000

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v3
      with:
        python-version: 3.10.6

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Start MLflow Server
      run: |
        mlflow server --host 127.0.0.1 --port 5000 &  # Run MLflow server in the background
        echo $! > mlflow_pid.txt

    - name: Run tests
      run: |
        pytest test_unitaires/
 
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Stop MLflow Server
      run: |
        if [ -f mlflow_pid.txt ]; then
          kill $(cat mlflow_pid.txt)
        else
          echo "mlflow_pid.txt not found"
        fi

